const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  load: () => ipcRenderer.invoke('accounts:load'),
  save: (accounts) => ipcRenderer.invoke('accounts:save', accounts),
  export: (accounts) => ipcRenderer.invoke('accounts:export', accounts),
  import: () => ipcRenderer.invoke('accounts:import'),
  resolveGame: (id) => ipcRenderer.invoke('game:resolve', id),
  searchGames: (query) => ipcRenderer.invoke('roblox:searchGames', query),
  enrich: (username) => ipcRenderer.invoke('roblox:enrich', username),
  enrichBatch: (usernames) => ipcRenderer.invoke('roblox:enrichBatch', usernames),
  openUrl: (url) => ipcRenderer.invoke('open:url', url),
  robloxLogin: (payload) => ipcRenderer.invoke('roblox:login', payload),
  bloxgenBalance: (apiKey) => ipcRenderer.invoke('bloxgen:balance', apiKey),
  bloxgenGenerate: (payload) => ipcRenderer.invoke('bloxgen:generate', payload),
  setCookie: (payload) => ipcRenderer.invoke('roblox:setCookie', payload),
  detect: (accountId) => ipcRenderer.invoke('roblox:detect', accountId),
  onDetected: (cb) => ipcRenderer.on('roblox:detected', (_e, data) => cb(data)),
  setTheme: (theme) => ipcRenderer.invoke('theme:set', theme),
  overlayDim: (on) => ipcRenderer.invoke('overlay:dim', on),
  version: () => ipcRenderer.invoke('app:version'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (_e, d) => cb(d)),
  onUpdateNone: (cb) => ipcRenderer.on('update:none', (_e, d) => cb(d)),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (_e, d) => cb(d)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', (_e, d) => cb(d)),
  onUpdateError: (cb) => ipcRenderer.on('update:error', (_e, d) => cb(d)),
  secureStatus: () => ipcRenderer.invoke('secure:status'),
  unlock: (password) => ipcRenderer.invoke('secure:unlock', password),
  setMasterPassword: (password, accounts) => ipcRenderer.invoke('secure:set', { password, accounts }),
  removeMasterPassword: (accounts) => ipcRenderer.invoke('secure:remove', { accounts }),
  openDataFolder: () => ipcRenderer.invoke('data:openFolder'),
  logoutAll: (ids) => ipcRenderer.invoke('roblox:logoutAll', ids),
  setConfig: (cfg) => ipcRenderer.invoke('config:set', cfg),
  confirm: (message, buttons) => ipcRenderer.invoke('ui:confirm', { message, buttons }),
});
